apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      name: monitor-pod
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor-container
          image: local/watcher
          imagePullPolicy: Never
