apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitor-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "CHANGE ME"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitor-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
