apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "CHANGE ME"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
